// Code generated by `cargo run --package generate`. DO NOT EDIT.

//! Emoji processing functionality.

use crate::SkinTone;
use crate::UnicodeVersion;
use serde::{Deserialize, Serialize};

/// A category for an emoji.
///
/// Based on Unicode CLDR data.
#[derive(Debug, Deserialize, Serialize, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Group {
    SmileysAndEmotion,
    PeopleAndBody,
    AnimalsAndNature,
    FoodAndDrink,
    TravelAndPlaces,
    Activities,
    Objects,
    Symbols,
    Flags,
}

/// Data about skin tone variants for an emoji.
#[derive(Clone, Deserialize, Serialize)]
pub struct SkinToneData {
    /// Index of the first skin tone variant in the EMOJIS array
    pub first: u16,
    /// Number of skin tone variants
    pub second: u8,
    /// The skin tone of this emoji
    pub tone: SkinTone,
}

/// Data about an emoji.
#[derive(Clone, Serialize)]
pub struct Emoji {
    /// The emoji character.
    pub emoji: String,
    /// The CLDR name of the emoji.
    pub name: String,
    /// The Unicode version when this emoji was added.
    pub unicode_version: UnicodeVersion,
    /// The group this emoji belongs to.
    pub group: Group,
    /// Skin tone information about this emoji.
    pub skin_tone: Option<SkinToneData>,
    /// Shortcodes/aliases for this emoji.
    pub aliases: Option<Vec<String>>,
}
