// Code generated by `cargo run --package generate`. DO NOT EDIT.

//! Emoji processing functionality.
mod gen;

pub use gen::{all_emojis, emoji_from_unicode, emoji_from_shortcode};

/// A category for an emoji.
///
/// Based on Unicode CLDR data.
#[derive(Debug, Clone, Copy, PartialEq, uniffi::Enum, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum Group {
   SmileysAndEmotion,
   PeopleAndBody,
   AnimalsAndNature,
   FoodAndDrink,
   TravelAndPlaces,
   Activities,
   Objects,
   Symbols,
   Flags,
}

/// Data about skin tone variants for an emoji.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Record)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SkinToneData {
    /// Index of the first skin tone variant in the EMOJIS array
    pub first: usize,
    /// Number of skin tone variants
    pub second: usize,
    /// The skin tone of this emoji
    pub tone: SkinTone,
}

/// Data about an emoji.
#[derive(Debug, Clone, uniffi::Record)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Emoji {
    /// The emoji character.
    pub emoji: String,
    /// The CLDR name of the emoji.
    pub name: String,
    /// The Unicode version when this emoji was added.
    pub unicode_version: UnicodeVersion,
    /// The group this emoji belongs to.
    pub group: Group,
    /// Skin tone information about this emoji.
    pub skin_tone: Option<SkinToneData>,
    /// Shortcodes/aliases for this emoji.
    pub aliases: Option<Vec<String>>,
}
